package: conda
user: conda

platform:
  - linux-32
  - linux-64
  - win-32
  - win-64
  # - osx-64

engine:
  - python=2
  - python=3.3
  - python=3.4
env:
  - CONDA_BUILD_TEST=1
  # Always kill the environment and work with root
  - CONDA_DEFAULT_ENV=

# Can't test on binstar because it needs to be installed in root
script:
  - conda build ./conda.recipe/

install:
  - conda update --name root --yes --quiet conda-build
  - python setup.py develop  # The ultimate dogfood. :-)

build_targets: conda
