repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # standard end of line/end of file cleanup
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # ensure syntaxes are valid
      - id: check-toml
      - id: check-yaml
      # catch git merge/rebase problems
      - id: check-merge-conflict
  - repo: https://github.com/akaihola/darker
    rev: 1.3.2
    hooks:
      - id: darker
        additional_dependencies: [black==21.9b0]
        exclude: ^conda/_vendor/
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==21.9b0]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/pylint
    rev: v2.11.1
    hooks:
      - id: pylint
        args: [--exit-zero]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [--exit-zero]
        exclude: ^(conda/_vendor|tests)/
