language: python
python:
  # We don't actually use the system Python but this keeps it organized.
  - "2.7"
  - "3.3"
install:
  # TODO: Use a "latest" url
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.0.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.0.0-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - python setup.py install
  - conda config --set always_yes yes
  - conda install nose

script: nosetests
