os:
  - linux
  - osx

addons:
  apt:
    packages:
    - zsh

env:
  global:
    - PYTHONUNBUFFERED=yes
  matrix:
    - PY_VERSION=2.7
    - PY_VERSION=3.4
    - PY_VERSION=3.5

install:
  - printenv
  - source ./utils/travis-bootstrap-conda.sh
  - conda install flake8 pytest mock
  - conda install pip
  - conda install psutil
  - pip install pytest-cov radon

script:
  - py.test --cov conda --cov-report xml tests --shell=bash --shell=zsh
  - radon cc --ignore "build,tests,ve,_vendor,progressbar" --no-assert -nb --total-average -s conda
  - radon mi --ignore "build,tests,ve,_vendor,progressbar" -na -m -s conda
  - flake8 --exit-zero --statistics
  - "[[ $PY_VERSION = 3.5 ]] || ./tests/run-integration"

sudo: false

git:
  depth: 3

after_success:
  - pip install codecov
  - codecov --env PY_VERSION
