language: python
sudo: false

addons:
  apt:
    packages:
      - zsh

matrix:
  include:
    - os: linux
      sudo: required
      python: '2.7'
      env: TOXENV=py27
    - os: linux
      sudo: required
      python: '3.4'
      env: TOXENV=py34
    - os: linux
      sudo: required
      python: '3.5'
      env: TOXENV=py35
    - os: osx
      language: generic
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py34
    - os: osx
      language: generic
      env: TOXENV=py35

before_install:
  - '[[ $(uname -s) == "Darwin" ]] && source utils/travis_bootstrap_conda.sh || true'
  - uname -a

install:
  - printenv
  - python --version
  - python setup.py sdist
  - pip install -U tox
  - cat $HOME/.conda/envs/test-environment/bin/tox

script:
  - printenv
  - tox -v

after_success:
  - pip install codecov
  - codecov --env TOX_ENV
