language: python
sudo: false
cache: false
python: '3.5'

env:
  global: PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35

cache:
  - $HOME/.pip-cache

before_install:
  - python --version
  - printenv
  - uname -a
  - lsb_release -a

install: travis_retry pip install -U tox

script: tox -v

addons:
  apt:
    packages:
      - zsh
