language: python

python:
  # We don't actually use the system Python but this keeps it organized.
  - "2.7"
  - "3.4"
  - "3.5"

os:
  - linux
  - osx

env:
  global:
    - PYTHONUNBUFFERED=yes

install:
  - printenv
  - source ./utils/travis-bootstrap-conda.sh
  - conda install pycosat requests conda-env pycrypto python=$TRAVIS_PYTHON_VERSION
  - conda install flake8 pytest mock pyflakes
  - conda install pip
  - pip install pytest-cov radon
  - python setup.py install

script:
  - shopt -s extglob globstar
  - pyflakes conda/**/!(compat|__init__).py bin setup.py tests
  - py.test --cov conda --cov-report xml tests
  - radon cc --ignore "build,tests,ve,_vendor,progressbar" --no-assert -nb --total-average -s conda
  - radon mi --ignore "build,tests,ve,_vendor,progressbar" -na -m -s conda
  - flake8 --exit-zero --statistics
  - conda --help

addons:
  apt:
    packages:
      - zsh

sudo: false

git:
  depth: 3

after_success:
  - pip install codecov
  - codecov --env TRAVIS_PYTHON_VERSION
