version: "3.9"

x-base: &base
  build:
    context: .
    # cache_from:
    #   - debian:buster-slim
    args:
      - python_version=${CONDA_DOCKER_PYTHON:-3.9}
  volumes:
    - .:/opt/conda-src
    - tmpfs:/tmp
  container_name: conda-linux-python-${CONDA_DOCKER_PYTHON:-3.9}

services:
  interactive:
    <<: *base
    command: ["bash", "--rcfile", "/opt/conda-src/dev/linux/bashrc.sh"]

  integration-tests:
    <<: *base
    command: ["bash", "/opt/conda-src/dev/linux/integration.sh"]

  unit-tests:
    <<: *base
    command: ["bash", "/opt/conda-src/dev/linux/unit.sh"]

volumes:
  tmpfs:
    driver_opts:
      type: tmpfs
      device: tmpfs
