[tool.black]
line-length = 99
target-version = ['py37', 'py38', 'py39', 'py310']
extend-exclude = '''
^/(
    conda/_vendor
  | devenv
)/
'''

[tool.vendoring]
destination = "conda/_vendor/"
requirements = "conda/_vendor/vendor.txt"
namespace = "conda._vendor"

protected-files = ["__init__.py", "vendor.txt", "README.md"]
patches-dir = "tools/vendoring/patches"

[tool.vendoring.transformations]
substitute = []
drop = [
  # contains unnecessary scripts
  "bin/",
  # remove unwanted modules
  '^boltons/(cache|debug|depr|dict|easter|eco|exc|file|format|func|gc|io|iter|json|list|math|mbox|named|path|queue|socket|stats|str|table|tb||type|url)utils\.py',
  "boltons/txurl_notes.md",
  "cpuinfo/__main__.py",
  "tlz/",
  '^toolz/(_signatures|functoolz)\.py',
  "toolz/curried",
  "toolz/sandbox",
  "toolz/tests",
  '^tqdm/.*(gui|notebook|pandas)\.py',
  '^tqdm/(_dist_ver|rich|keras|tk|dask)\.py',
  '^tqdm/(completion\.sh|tqdm\.1)',
  "tqdm/contrib",
]

[tool.vendoring.typing-stubs]
# prevent stubs from being generated
boltons = []
toolz = []
tqdm = []
appdirs = []
cpuinfo = []
distro = []
frozendict = []
six = []

[tool.vendoring.license.fallback-urls]
boltons = "https://raw.githubusercontent.com/mahmoud/boltons/master/LICENSE"  # BSD
toolz = "https://raw.githubusercontent.com/pytoolz/toolz/master/LICENSE.txt"  # BSD
tqdm = "https://raw.githubusercontent.com/tqdm/tqdm/master/LICENCE"  # MPL, MIT
appdirs = "https://raw.githubusercontent.com/ActiveState/appdirs/master/LICENSE.txt"  # MIT
cpuinfo = "https://raw.githubusercontent.com/workhorsy/py-cpuinfo/master/LICENSE"  # MIT
distro = "https://raw.githubusercontent.com/python-distro/distro/master/LICENSE"  # Apache
frozendict = "https://raw.githubusercontent.com/Marco-Sulla/python-frozendict/master/LICENSE.txt"  # LGPL
six = "https://raw.githubusercontent.com/benjaminp/six/master/LICENSE"  # MIT

[tool.pytest.ini_options]
minversion = "3.0"
testpaths = "conda tests"
norecursedirs = ".* *.egg* build dist env ve conda/_vendor/* conda_env/* test_data/*"
addopts = """
--ignore setup.py
--ignore conda/__main__.py
--ignore conda/_vendor
--ignore tests/conda_env/specs/test_binstar.py
--ignore tests/conda_env/support
--ignore tests/conda_env/utils/test_uploader.py
--ignore test_data
--tb native
--strict-markers
--durations 16
--xdoctest-modules
--xdoctest-style=google
--cov-report xml
--cov-report term-missing
--cov conda
--cov-append
--junitxml=test-report.xml"""
doctest_optionflags = """
NORMALIZE_WHITESPACE
IGNORE_EXCEPTION_DETAIL
ALLOW_UNICODE
ELLIPSIS"""
markers = """
integration: integration tests that usually require an internet connect
slow: slow running tests
"""
