name: 'Canary releases'
description: 'This builds and uploads canary releases of conda to the provided channel and label on anaconda.org.'
inputs:
  pr:
    description: 'Pull request ID'
    required: true
  package-name:
    description: 'Name of package on anaconda.org, needs to match build file name.'
    required: true
  subdir:
    description: 'Subdirectory'
    required: true
  comment-token:
    description: 'Token for commenting build'
    required: false
  anaconda-org-channel:
    description: 'Channel on anaconda.org'
    required: true
  anaconda-org-label:
    description: 'Label to use on anaconda.org'
    required: true
  anaconda-org-token:
    description: 'Upload token for anaconda.org'
    required: true
runs:
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@v2

    - name: Create URL to the run output
      id: vars
      shell: bash -l {0}
      run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

    - name: Find Comment
      uses: peter-evans/find-comment@v1
      if: inputs.comment-token != ''
      id: find-comment
      with:
        issue-number: ${{ inputs.pr }}
        comment-author: conda-bot
        body-includes: The canary build for
        direction: last

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      if: |
        steps.find-comment.outputs.comment-id == '' &&
        inputs.comment-token != ''
      id: create-comment
      with:
        issue-number: ${{ inputs.pr }}
        body: |
          The canary build for ${{ inputs.package-name }} with the label `${{ inputs.anaconda-org-label }}` in channel `${{ inputs.anaconda-org-channel }}` [has started][1]!

          [1]: ${{ steps.vars.outputs.run-url }}
        reactions: 'rocket'
        token: ${{ inputs.comment-token }}

    - name: Build & upload package
      # make sure we don't run on forks
      if: |
        github.repository_owner == 'conda' &&
        steps.create-comment.outcome == 'success'
      id: build
      shell: bash -l {0}
      run: |
        echo "::group::Setting up environment"
        set -euo pipefail
        conda activate
        conda update --yes --quiet conda
        conda install --yes --quiet conda-build anaconda-client git
        echo "::endgroup::"

        echo "::group::Debugging information"
        conda info
        conda config --show-sources
        conda list
        echo "::endgroup::"

        echo "::group::Building package"
        conda build --croot=./pkgs conda.recipe
        echo "::endgroup::"

        echo "::group::Uploading package"
        anaconda --token ${{ inputs.anaconda-org-token }} upload \
          --force --register --no-progress \
          --user ${{ inputs.anaconda-org-channel }} \
          --label ${{ inputs.anaconda-org-label }} \
          ./pkgs/${{ inputs.subdir }}/${{ inputs.package-name }}-*.tar.bz2
        echo "Uploaded the following files:"
        ls ./pkgs/${{ inputs.subdir }}/${{ inputs.package-name }}-*.tar.bz2 | cut -d/ -f3- | tr ' ' $'\n'
        echo "::endgroup::"

        echo "Use this command to try out the build:"
        echo "conda install -c ${{ inputs.anaconda-org-channel }}/label/${{ inputs.anaconda-org-label }} ${{ inputs.package-name }}"

    - name: Update comment (failure)
      if: |
        steps.create-comment.outputs.comment-id != '' &&
        steps.build.outcome == 'failure' &&
        inputs.comment-token != ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.create-comment.outputs.comment-id }}
        body: |
          The build failed! Please check the [workflow run][1] for errors.

          [1]: ${{ steps.vars.outputs.run-url }}
        reactions: 'eyes'
        token: ${{ inputs.comment-token }}

    - name: Update comment (success)
      if: |
        steps.create-comment.outputs.comment-id != '' &&
        steps.build.outcome == 'success' &&
        inputs.comment-token != ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.create-comment.outputs.comment-id }}
        body: |
          Build successful! Use this command to try it out in an
          empty conda environment:

          ```
          conda install -c ${{ inputs.anaconda-org-channel }}/label/${{ inputs.anaconda-org-label }} ${{ inputs.package-name }}
          ```
        reactions: 'hooray'
        token: ${{ inputs.comment-token }}
