package:
  name: conda-env
  version: 1.1.0

build:
  number: 100
  # TODO Re-enable this once conda-build and/or binstar-build plays nicely
  # number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  # string: {{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}
  preserve_egg_dir: yes

# source:
#   git_url: ..

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  commands:
    - conda env -h
    - conda env list -h
    - conda env create -h
    - conda env export -h
    - conda env remove -h

about:
  home: https://github.com/conda/conda-env/
