package:
  name: conda

source:
  path: ../

build:
  # These are present when the new environment is created
  # so we have to exempt them from the list of initial files
  # for conda-build to realize they should be included.
  always_include_files:
    - bin/conda                 [unix]
    - bin/activate              [unix]
    - bin/deactivate            [unix]
    - Scripts/activate.bat      [win]
    - Scripts/deactivate.bat    [win]
    # TODO: are these needed?  They currently break packaging, since these files don't exist yet at build time
    # - Scripts/activate          [win]
    # - Scripts/deactivate        [win]
    # TODO: what about fish and powershell?

  entry_points:
    - conda = conda.cli:main

requirements:
  build:
    - python
    - conda-env
    - menuinst  [win]
    - psutil
    - pycosat >=0.6.1
    - pyyaml
    - raml
    - requests
  run:
    - python
    - conda-env
    - menuinst  [win]
    - psutil
    - pycosat >=0.6.1
    - pyyaml
    - raml
    - requests

test:
  commands:
    - conda --version
    - conda info
  imports:
    - conda

about:
  home: http://conda.pydata.org/
  license: BSD
  license_file: LICENSE.txt
  summary: OS-agnostic, system-level binary package manager.
