name: Review builds

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    if: |
      github.event_name == 'pull_request' &&
      github.event.label.name == 'build::review'
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            subdir: linux-64
          - runner: macos-latest
            subdir: osx-64
          - runner: windows-latest
            subdir: win-64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0

      - name: Create and upload review build
        uses: ./.github/actions/canary
        with:
          channel: conda-canary
          name: conda
          subdir: ${{ matrix.subdir }}
          label: ${{ github.repository_owner }}-${{ github.event.repository.name }}-pr-${{ github.event.number }}
          token: ${{ secrets.ANACONDA_ORG_TOKEN }}
          pr: ${{ github.event.number }}

      - name: Remove build label
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: github.event.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [github.event.label.name]
            })
