name: Review builds

on:
  # NOTE: github.event context is pull_request payload:
  # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
  pull_request:
    types:
      - labeled

jobs:
  build:
    if: >-
      !github.event.repository.fork
      && github.event.label.name == 'build::review'
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            subdir: linux-64
          - runner: macos-latest
            subdir: osx-64
          - runner: windows-latest
            subdir: win-64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Remove build label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CANARY_ACTION_TOKEN }}
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.issue.number,
            })
            const buildLabel = '${{ github.event.label.name }}'
            const labels = pullRequest.labels.map(label => label.name)
            const hasBuildLabel = labels.includes(buildLabel)

            if (hasBuildLabel) {
                await github.rest.issues.removeLabel({
                  ...context.repo,
                  issue_number: context.issue.number,
                  name: buildLabel,
                })
            }

      # Clean checkout of specific git ref needed for package metadata version
      # which needs env vars GIT_DESCRIBE_TAG and GIT_BUILD_STR:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true

      - name: Build & upload package
        # make sure we don't run on forks
        id: build
        shell: bash -l {0}
        run: |
          echo "::group::Setting up environment"
          set -euo pipefail
          conda activate
          conda update --yes --quiet conda
          conda install --yes --quiet conda-build anaconda-client git
          echo "::endgroup::"

          echo "::group::Debugging information"
          conda info
          conda config --show-sources
          conda list
          echo "::endgroup::"

          echo "::group::Building package"
          conda build --croot=./pkgs recipe
          echo "::endgroup::"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: always()
