name: Review builds

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    if: |
      github.event_name == 'pull_request' &&
      github.event.label.name == 'build::review'
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            subdir: linux-64
          - runner: macos-latest
            subdir: osx-64
          - runner: windows-latest
            subdir: win-64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
      - uses: ./github/actions/canary
        with:
          channel: conda-canary
          label: ${{ github.repository_owner }}-${{ github.event.repository.name }}-pr-${{ github.event.number }}
          token: ${{ secrets.ANACONDA_ORG_TOKEN }}
