name: CI tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  windows:
    name: Windows (py${{ matrix.python_version }}, ${{ matrix.test_type }} tests, group ${{ matrix.test_group }}/${{ env.GROUP_COUNT }})
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.7, 3.8, 3.9]
        conda_subdir: ['win-64']
        test_type: ['unit', 'integration']
        test_group: ['1', '2', '3', '4']
    env:
      OS: 'win-64'
      PYTHON: ${{ matrix.python_version }}
      CONDA_SUBDIR: ${{ matrix.conda_subdir }}
      GROUP_COUNT: 4
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set temp dirs correctly
      shell: bash -l {0}
      # https://github.com/actions/virtual-environments/issues/712
      run: |
        echo "TMPDIR=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV
        echo "TEMP=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV
        echo "TMP=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV

    - name: Setup environment
      shell: cmd
      run: |
        call ./tests/scripts/setup.bat

    - name: py${{ matrix.python_version }} ${{ matrix.conda_subdir }} ${{ matrix.test_type }} tests
      shell: cmd
      run: |
        call ./tests/scripts/${{ matrix.test_type }}_tests.bat
      env:
        TEST_GROUP: ${{ matrix.test_group }}

    - uses: codecov/codecov-action@v2
      with:
        flags: ${{ matrix.test_type }}
        env_vars: OS,PYTHON

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run : |
          make env-lint
      - name: flake8
        run : |
          conda run --name conda-lint make lint

  linux:
    name: Linux (py${{ matrix.python_version }}, ${{ matrix.test_type }} tests, group ${{ matrix.test_group }}/${{ env.GROUP_COUNT }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.7', '3.8', '3.9']
        test_type: ['unit', 'integration']
        test_group: ['1', '2', '3', '4']
    env:
      OS: 'linux'
      PYTHON: ${{ matrix.python_version }}
      GROUP_COUNT: 4
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Python ${{ matrix.python_version }} ${{ matrix.test_type }} tests
        run: docker run --rm -v ${PWD}:/opt/conda-src -e GROUP_COUNT -e TEST_GROUP ghcr.io/conda/conda-ci:test-improvements-linux-python${{ matrix.python_version }} /opt/conda-src/tests/${{ matrix.test_type }}_tests.sh
        env:
          TEST_GROUP: ${{ matrix.test_group }}

      - uses: codecov/codecov-action@v2
        with:
          flags: ${{ matrix.test_type }}
          env_vars: OS,PYTHON
