name: CI tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        conda-subdir: ['win-64']
        test-type: ['unit', 'integration']
        test-group: ['1', '2', '3', '4']
    env:
      OS: 'win-64'
      PYTHON: ${{ matrix.python-version }}
      CONDA_SUBDIR: ${{ matrix.conda-subdir }}
      TEST_SPLITS: 4
      TEST_GROUP: ${{ matrix.test-group }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set temp dirs correctly
      shell: bash -l {0}
      # https://github.com/actions/virtual-environments/issues/712
      run: |
        echo "TMPDIR=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV
        echo "TEMP=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV
        echo "TMP=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV

    - name: Setup environment
      shell: cmd
      run: |
        call ./tests/scripts/windows/setup.bat

    - name: py${{ matrix.python-version }} ${{ matrix.conda-subdir }} ${{ matrix.test-type }} tests
      shell: cmd
      run: |
        call ./tests/scripts/windows/${{ matrix.test-type }}.bat

    - uses: codecov/codecov-action@v2
      with:
        flags: ${{ matrix.test-type }}
        env_vars: OS,PYTHON

  lint:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        if: ${{ matrix.platform }} != "ubuntu-latest"
      - name: Setup
        run : |
          make env-lint
      - name: flake8
        run : |
          conda run --name conda-lint make lint

  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9']
        test-type: ['unit', 'integration']
        test-group: ['1', '2', '3', '4']
    env:
      OS: 'linux'
      PYTHON: ${{ matrix.python-version }}
      TEST_SPLITS: 4
      TEST_GROUP: ${{ matrix.test-group }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Python ${{ matrix.python-version }} ${{ matrix.test_type }} tests
        run: >
          docker run
          --rm -v ${PWD}:/opt/conda-src
          -e TEST_SPLITS
          -e TEST_GROUP
          ghcr.io/conda/conda-ci:pr-10864-linux-python${{ matrix.python-version }}
          /opt/conda-src/tests/scripts/linux/${{ matrix.test-type }}.sh

      - uses: codecov/codecov-action@v2
        with:
          flags: ${{ matrix.test-type }}
          env_vars: OS,PYTHON
