name: Lint

defaults:
  run:
    shell: bash -l {0}

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  lint:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Fix Conda permissions on macOS
        if: runner.os == 'macOS'
        run: sudo chown -R $UID $CONDA

      - name: Setup
        run : |
          conda install flake8

      - name: flake8
        run : |
          flake8 --statistics
